/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAffix: (typeof import('ant-design-vue/es'))['Affix'];
    AButton: (typeof import('ant-design-vue/es'))['Button'];
    ACheckbox: (typeof import('ant-design-vue/es'))['Checkbox'];
    ACheckboxGroup: (typeof import('ant-design-vue/es'))['CheckboxGroup'];
    ADropdown: (typeof import('ant-design-vue/es'))['Dropdown'];
    AForm: (typeof import('ant-design-vue/es'))['Form'];
    AFormItem: (typeof import('ant-design-vue/es'))['FormItem'];
    AInput: (typeof import('ant-design-vue/es'))['Input'];
    ALayout: (typeof import('ant-design-vue/es'))['Layout'];
    ALayoutContent: (typeof import('ant-design-vue/es'))['LayoutContent'];
    ALayoutFooter: (typeof import('ant-design-vue/es'))['LayoutFooter'];
    ALayoutHeader: (typeof import('ant-design-vue/es'))['LayoutHeader'];
    ALayoutSider: (typeof import('ant-design-vue/es'))['LayoutSider'];
    AMenu: (typeof import('ant-design-vue/es'))['Menu'];
    AMenuItem: (typeof import('ant-design-vue/es'))['MenuItem'];
    ARadio: (typeof import('ant-design-vue/es'))['Radio'];
    ARadioGroup: (typeof import('ant-design-vue/es'))['RadioGroup'];
    ASelect: (typeof import('ant-design-vue/es'))['Select'];
    ASpin: (typeof import('ant-design-vue/es'))['Spin'];
    ASwitch: (typeof import('ant-design-vue/es'))['Switch'];
    ATabPane: (typeof import('ant-design-vue/es'))['TabPane'];
    ATabs: (typeof import('ant-design-vue/es'))['Tabs'];
    ATextarea: (typeof import('ant-design-vue/es'))['Textarea'];
    ContextMenu: (typeof import('./src/components/context-menu/index.vue'))['default'];
    GithubSync: (typeof import('./src/components/settings-menu/components/github-sync.vue'))['default'];
    SearchConfig: (typeof import('./src/components/settings-menu/components/search-config.vue'))['default'];
    SearchSelect: (typeof import('./src/components/search-select/index.vue'))['default'];
    SettingMenu: (typeof import('./src/components/setting-menu/index.vue'))['default'];
    SettingsMenu: (typeof import('./src/components/settings-menu/index.vue'))['default'];
    SettingsTab: (typeof import('./src/components/settings-tab/index.vue'))['default'];
  }
}
